# Generated by Django 5.0.6 on 2024-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_obras_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='id_artista',
            field=models.AutoField(db_column='idArtista', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obras',
            name='id_obra',
            field=models.AutoField(db_column='idObra', primary_key=True, serialize=False),
        ),
    ]
