# Generated by Django 5.0.6 on 2024-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_artista_id_artista_alter_obras_id_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imgUrl',
            field=models.CharField(default='https://img.freepik.com/foto-gratis/paleta-colores-sucios-tubos-acuarela_23-2148662999.jpg?t=st=1720018054~exp=1720021654~hmac=4279a3e9f9ffcff619ad6a5131bc6ae5dc3b5f071f3e237e1c1b2f1406a32c64&w=996', max_length=255),
        ),
    ]
