# Generated by Django 5.0.6 on 2024-07-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_artista_id_genero_remove_obras_id_artista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='imgUrl',
            field=models.CharField(default='https://img.freepik.com/foto-gratis/paleta-colores-sucios-tubos-acuarela_23-2148662999.jpg?t=st=1720018054~exp=1720021654~hmac=4279a3e9f9ffcff619ad6a5131bc6ae5dc3b5f071f3e237e1c1b2f1406a32c64&w=996', max_length=500),
        ),
    ]
