# Generated by Django 5.0.6 on 2024-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_obras_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='precio',
            field=models.IntegerField(default=1000),
        ),
    ]
